import Head from "next/head";
// import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      {/* internal style  */}
      {/* if you went to use this class in any other component the use global keyword with jsx 
    for Example  */}

      {/* <style jsx global>
        {`
          .mySpan {
            color: red;
          }
        `}
      </style> */}
      <style jsx>
        {`
          h2 {
            font-size: 38px;
            margin-bottom: 15px;
          }
          h3 {
            font-size: 20px;
          }
        `}
      </style>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.description}>
          <h1>Hunting Coder</h1>
        </div>

        <div className={styles.imgWraper}>
          {/* <Image
            src="/homeimg.avif"
            alt="home"
            height={150}
            width={200}
            className={styles.myimg}
          /> */}
          <img
            src="/homeimg.avif"
            alt="home"
            height={150}
            width={200}
            className={styles.myimg}
          />
        </div>
        <p>A blog for hunting coder by hunting coder</p>
        <div className={styles.blogs}>
          <div className={styles.blogsItems}>
            <h2>Famous Bologs</h2>
            <h3>How to Start with Next JS</h3>
            <p>Next JS is a framwork of React JS</p>
          </div>
          <div className={styles.blogsItems}>
            <h3>How to Start with Next JS</h3>
            <p>Next JS is a framwork of React JS</p>
          </div>
          <div className={styles.blogsItems}>
            <h3>How to Start with Next JS</h3>
            <p>Next JS is a framwork of React JS</p>
          </div>
        </div>
      </main>
    </>
  );
}
